# Generated by Django 6.0.2 on 2026-02-23 09:53

import django.db.models.deletion
from django.db import migrations, models


def migrate_departments(apps, schema_editor):
    """Create Department objects from existing department names and link teachers."""
    Teacher = apps.get_model('faculty', 'Teacher')
    Department = apps.get_model('faculty', 'Department')

    # Get unique department names
    dept_names = Teacher.objects.exclude(department_old__isnull=True).exclude(department_old='').values_list('department_old', flat=True).distinct()

    for dept_name in dept_names:
        # Create a code from the department name
        code = ''.join(word[0].upper() for word in dept_name.split()[:3])
        if not code:
            code = dept_name[:3].upper()

        # Make sure code is unique
        base_code = code
        counter = 1
        while Department.objects.filter(code=code).exists():
            code = f"{base_code}{counter}"
            counter += 1

        dept, created = Department.objects.get_or_create(
            name=dept_name,
            defaults={'code': code}
        )

        # Link teachers to this department
        Teacher.objects.filter(department_old=dept_name).update(department=dept)


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy department names back."""
    Teacher = apps.get_model('faculty', 'Teacher')
    for teacher in Teacher.objects.filter(department__isnull=False):
        teacher.department_old = teacher.department.name
        teacher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        # Step 1: Rename the existing CharField to department_old
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='department_old',
        ),
        # Step 2: Create the Department model
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the department (e.g., CS, IT, EE)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Step 3: Add the new department FK field
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='faculty.department'),
        ),
        # Step 4: Migrate data from department_old to new Department model
        migrations.RunPython(migrate_departments, reverse_migrate),
        # Step 5: Remove the old department_old field
        migrations.RemoveField(
            model_name='teacher',
            name='department_old',
        ),
    ]
